export enum Endpoints {
  businessCreate = "business/create",
  business = "business",
  businessUpdate = "business/update",
  myBusinesses = "business/my",
  items = "business/items",
  verification = "business/forceverify",
  businessOrders = "business/orders",
  deleteBusiness = "business/delete",
  deleteItems = "business/itemsdelete",
  createItem = "business/itemscreate",
  acceptOrder = "business/orderaccept",
  declineOrder = "business/orderdecline",
  categories = "business/categories",
}
